### PR TITLE
Update 3dsmax.ps1

### PR DESCRIPTION
**Pull request by davidkydd**
Fix the targeted .exe to one which includes Batch licensing

### CODE REVIEW

**Comment by pipoun** [comment]
Unfortunately 3dsmaxio.exe MUST be used, not 3dsmaxiocmd.exe.
3dsmaxiocmd lacks functionalities needed for our purposes.

**Comment by davidkydd** [comment]
@pipoun I ran some tests today but was unable to repro the licensing issue from VRay when targeting 3dsmaxio.exe using the changes in your branch - I encountered different issues in the 3dsmax log around missing files, and VRay appeared to open and generated what looked like a healthy vraylog file, but never requested a license. Unfortunately we have never attempted this scenario ourselves so it is formally unsupported, and I suspect the licensing failure you saw is expected. The best suggestion I have is to run your own vray license server on a dedicated azure VM and connect the nodes in your Batch pool to it.

**Comment by pipoun** [comment]
@davidkydd thanks for the investigation. That's very bad news. Usable based licencing for 3ds Max and V-Ray was a great feature.

Do you have a procedure to "connect" the nodes in our batch pool to a vray licence server ?
We are using VM images shipped by azure with "special" 3ds max version ("io" flavored). Actually what is missing is the "io" version of 3dsmaxbatch.exe. Do you have plans to support this ?
Neither we manage the installation of V-Ray, so I don't know how we can change the license request procedure.

**Comment by davidkydd** [comment]
No plans to support io version of 3dsmaxbatch.exe unfortunately. Also no standard procedure for standing up a license server, this would be roughly the same process as connecting a license server to a set of raw azure VMs for rendering, but the VMs are members of a Batch pool

**Comment by davefellows** [comment]
3ds Max (IO) will check to see if has a Batch licensing token, if this isn't present, then it will fall back to the usual license server mechanism. Just setup the license server as you would on-prem and make sure you have network connectivity between the Batch nodes and the license server VM (e.g. within the same VNet). Configure the license server's IP address in 3ds Max (you may need to do this with a startup script to patch in the license server details - I'm not sure exactly how this is configured in 3ds Max)...

**Comment by pipoun** [comment]
OK, I see roughly the procedure. Not sure which is the simpler way, use the VM images shipped by azure and patch on startup, or install a new one from a vanilla windows server image.

**Pull request closed without merging**
